In [4]:
import json
import pandas as pd
from python_submodule.general import info, warning, error, debug

In [ ]:
train_data = json.load(open("data/test_with_timestamps.json"))
test_data = json.load(open("data/test_with_timestamps.json"))
metadata = json.load(open("data/thinned_poi_metadata.json"))

In [22]:
session_id = 0
train_dict = {"SessionId": [], "ItemId": [], "Time": []}

for e in train_data:
    if len(e["history_events"]) == 1:
        session_id += 1
        train_dict["SessionId"].append(session_id)
        train_dict["ItemId"].append(e["history_events"][0]["item_id"])
        train_dict["Time"].append(e["history_events"][0]["timestamp"])
    train_dict["SessionId"].append(session_id)
    train_dict["ItemId"].append(e["target_event"]["item_id"])
    train_dict["Time"].append(e["target_event"]["timestamp"])

train_df = pd.DataFrame(train_dict)

In [24]:
session_id = 0
test_dict = {"SessionId": [], "ItemId": [], "Time": []}

for e in test_data:
    if len(e["history_events"]) == 1:
        session_id += 1
        test_dict["SessionId"].append(session_id)
        test_dict["ItemId"].append(e["history_events"][0]["item_id"])
        test_dict["Time"].append(e["history_events"][0]["timestamp"])
    test_dict["SessionId"].append(session_id)
    test_dict["ItemId"].append(e["target_event"]["item_id"])
    test_dict["Time"].append(e["target_event"]["timestamp"])

test_df = pd.DataFrame(test_dict)

In [46]:
train_df["Time"] = pd.to_datetime(train_df["Time"]).astype('int64') // 10**9
test_df["Time"] = pd.to_datetime(test_df["Time"]).astype('int64') // 10**9

In [47]:
train_df.head()

   SessionId  ItemId     Time
0          1       1  1274496
1          1       2  1274550
2          1       3  1274633
3          2       4  1275336
4          2       5  1275403

In [48]:
test_df.head()

   SessionId  ItemId     Time
0          1    2874  1284228
1          1     445  1284245
2          1    1089  1284310
3          1    1139  1284340
4          1     729  1284400

In [49]:
info(len(train_df["SessionId"]))
info(len(test_df["SessionId"]))

INFO   909728
INFO   212652

In [50]:
info(train_df["SessionId"].nunique())
info(test_df["SessionId"].nunique())

INFO   234461
INFO   57520

In [51]:
train_df.to_csv("data/train.csv", index=False)
test_df.to_csv("data/test.csv", index=False)

In [53]:
train_df.to_pickle('data/train.pickle')
test_df.to_pickle('data/test.pickle')